note that this will crash if your cpu doesn't have avx2 instructions

In [1]:
import intake
import intake_esm
import xarray as xr

In [2]:
catalog_url = '/work/a3r/catalogs/data2_cmip/catalog.json'

In [3]:
cat = intake.open_esm_datastore(catalog_url)

In [6]:
cat.unique()

activity_id                                                         [NA]
institution_id                                               [NOAA-GFDL]
source_id                                               [GFDL-SPEAR-MED]
experiment_id                              [historical, scenarioSSP5-85]
frequency                                                           [NA]
realm                                                               [NA]
table_id                                          [Amon, day, Omon, 6hr]
member_id              [r5i1p1f1, r4i1p1f1, r6i1p1f1, r7i1p1f1, r8i1p...
grid_label                                                     [gr3, gr]
variable_id            [zg, tas, pr, psl, uas, vas, rlut, rsdt, rsut,...
version_id                                                   [v20210201]
time_range             [192101-201412, 19910101-20001231, 19210101-19...
chunk_freq                                                          [NA]
platform                                                            [NA]
dimensions                                                          [NA]
cell_methods                                                        [NA]
standard_name          [geopotential_height, air_temperature, precipi...
path                   [/data/2/GFDL-LARGE-ENSEMBLES/CMIP/NOAA-GFDL/G...
derived_variable_id                                                   []
dtype: object

In [12]:
cat_subset = cat.search(
    variable_id='tas', 
    experiment_id='historical', 
    time_range=['19210101-19301231', '19310101-19401231']
)
cat_subset

In [13]:
dset_dict = cat_subset.to_dataset_dict(
    xarray_open_kwargs={"consolidated": True, "decode_times": True, "use_cftime": True}
)

--> The keys in the returned dictionary of datasets are constructed as follows:
	'source_id.experiment_id.frequency.table_id.grid_label.realm.member_id.chunk_freq'

```html
<div>
<progress max="30" value="0"></progress> 0.00% [0/30 00:00&lt;?]</div>

```

ESMDataSourceError: Failed to load dataset with key='GFDL-SPEAR-MED.historical.NA.day.gr3.NA.r1i1p1f1.NA'
                 You can use `cat['GFDL-SPEAR-MED.historical.NA.day.gr3.NA.r1i1p1f1.NA'].df` to inspect the assets/files for this key.

In [14]:
cat['GFDL-SPEAR-MED.historical.NA.day.gr3.NA.r1i1p1f1.NA'].df

,activity_id,institution_id,source_id,experiment_id,frequency,realm,table_id,member_id,grid_label,variable_id,version_id,time_range,chunk_freq,platform,dimensions,cell_methods,standard_name,path,_data_format_
0,NA,NOAA-GFDL,GFDL-SPEAR-MED,historical,NA,NA,day,r1i1p1f1,gr3,psl,v20210201,19810101-19901231,NA,NA,NA,NA,air_pressure_at_mean_sea_level,/data/2/GFDL-LARGE-ENSEMBLES/CMIP/NOAA-GFDL/GF...,netcdf
1,NA,NOAA-GFDL,GFDL-SPEAR-MED,historical,NA,NA,day,r1i1p1f1,gr3,psl,v20210201,20110101-20141231,NA,NA,NA,NA,air_pressure_at_mean_sea_level,/data/2/GFDL-LARGE-ENSEMBLES/CMIP/NOAA-GFDL/GF...,netcdf
2,NA,NOAA-GFDL,GFDL-SPEAR-MED,historical,NA,NA,day,r1i1p1f1,gr3,psl,v20210201,19210101-19301231,NA,NA,NA,NA,air_pressure_at_mean_sea_level,/data/2/GFDL-LARGE-ENSEMBLES/CMIP/NOAA-GFDL/GF...,netcdf
3,NA,NOAA-GFDL,GFDL-SPEAR-MED,historical,NA,NA,day,r1i1p1f1,gr3,psl,v20210201,19510101-19601231,NA,NA,NA,NA,air_pressure_at_mean_sea_level,/data/2/GFDL-LARGE-ENSEMBLES/CMIP/NOAA-GFDL/GF...,netcdf
4,NA,NOAA-GFDL,GFDL-SPEAR-MED,historical,NA,NA,day,r1i1p1f1,gr3,psl,v20210201,20010101-20101231,NA,NA,NA,NA,air_pressure_at_mean_sea_level,/data/2/GFDL-LARGE-ENSEMBLES/CMIP/NOAA-GFDL/GF...,netcdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,NA,NOAA-GFDL,GFDL-SPEAR-MED,historical,NA,NA,day,r1i1p1f1,gr3,vas,v20210201,19610101-19701231,NA,NA,NA,NA,northward_wind,/data/2/GFDL-LARGE-ENSEMBLES/CMIP/NOAA-GFDL/GF...,netcdf
66,NA,NOAA-GFDL,GFDL-SPEAR-MED,historical,NA,NA,day,r1i1p1f1,gr3,vas,v20210201,20110101-20141231,NA,NA,NA,NA,northward_wind,/data/2/GFDL-LARGE-ENSEMBLES/CMIP/NOAA-GFDL/GF...,netcdf
67,NA,NOAA-GFDL,GFDL-SPEAR-MED,historical,NA,NA,day,r1i1p1f1,gr3,vas,v20210201,19410101-19501231,NA,NA,NA,NA,northward_wind,/data/2/GFDL-LARGE-ENSEMBLES/CMIP/NOAA-GFDL/GF...,netcdf
68,NA,NOAA-GFDL,GFDL-SPEAR-MED,historical,NA,NA,day,r1i1p1f1,gr3,vas,v20210201,19810101-19901231,NA,NA,NA,NA,northward_wind,/data/2/GFDL-LARGE-ENSEMBLES/CMIP/NOAA-GFDL/GF...,netcdf
69,NA,NOAA-GFDL,GFDL-SPEAR-MED,historical,NA,NA,day,r1i1p1f1,gr3,vas,v20210201,19910101-20001231,NA,NA,NA,NA,northward_wind,/data/2/GFDL-LARGE-ENSEMBLES/CMIP/NOAA-GFDL/GF...,netcdf